//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihelcic.Net.Visio.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShapeRsx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShapeRsx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mihelcic.Net.Visio.Data.ShapeRsx", typeof(ShapeRsx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string ConnPointPfx {
            get {
                return ResourceManager.GetString("ConnPointPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string DCPfx {
            get {
                return ResourceManager.GetString("DCPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Controller.
        /// </summary>
        public static string DCShape {
            get {
                return ResourceManager.GetString("DCShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string DomainPfx {
            get {
                return ResourceManager.GetString("DomainPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD-Domain.
        /// </summary>
        public static string DomainShape {
            get {
                return ResourceManager.GetString("DomainShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Catalog.
        /// </summary>
        public static string GCShape {
            get {
                return ResourceManager.GetString("GCShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Replication InterSit.
        /// </summary>
        public static string InterConnShape {
            get {
                return ResourceManager.GetString("InterConnShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Replication IntraSit.
        /// </summary>
        public static string IntraConnShape {
            get {
                return ResourceManager.GetString("IntraConnShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm.
        /// </summary>
        public static string RealmPfx {
            get {
                return ResourceManager.GetString("RealmPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT-Domain.
        /// </summary>
        public static string RealmShape {
            get {
                return ResourceManager.GetString("RealmShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlyDomain Controller.41.
        /// </summary>
        public static string RODCShape {
            get {
                return ResourceManager.GetString("RODCShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string ShapeToColor {
            get {
                return ResourceManager.GetString("ShapeToColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        public static string SiteLinkPfx {
            get {
                return ResourceManager.GetString("SiteLinkPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Site Link.
        /// </summary>
        public static string SiteLinkShape {
            get {
                return ResourceManager.GetString("SiteLinkShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SitePfx {
            get {
                return ResourceManager.GetString("SitePfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SiteShape {
            get {
                return ResourceManager.GetString("SiteShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2000 Trust.
        /// </summary>
        public static string Trust2000Shape {
            get {
                return ResourceManager.GetString("Trust2000Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Forest Trust.
        /// </summary>
        public static string TrustCrossForestShape {
            get {
                return ResourceManager.GetString("TrustCrossForestShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downlevel Trust.
        /// </summary>
        public static string TrustDownShape {
            get {
                return ResourceManager.GetString("TrustDownShape", resourceCulture);
            }
        }
    }
}
