//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihelcic.Net.Visio.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mihelcic.Net.Visio.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Notification: {0}.
        /// </summary>
        public static string ChangeNotifComment {
            get {
                return ResourceManager.GetString("ChangeNotifComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost: {0}.
        /// </summary>
        public static string CostComment {
            get {
                return ResourceManager.GetString("CostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFL: {0}.
        /// </summary>
        public static string DFLComment {
            get {
                return ResourceManager.GetString("DFLComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN master: {0}.
        /// </summary>
        public static string DnMasterComment {
            get {
                return ResourceManager.GetString("DnMasterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFL: {0}.
        /// </summary>
        public static string FFLComment {
            get {
                return ResourceManager.GetString("FFLComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Catalog.
        /// </summary>
        public static string GCComment {
            get {
                return ResourceManager.GetString("GCComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM: {0}.
        /// </summary>
        public static string IMComment {
            get {
                return ResourceManager.GetString("IMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval: {0}.
        /// </summary>
        public static string IntervalComment {
            get {
                return ResourceManager.GetString("IntervalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISTG: {0}.
        /// </summary>
        public static string IstgOutput {
            get {
                return ResourceManager.GetString("IstgOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string NameComment {
            get {
                return ResourceManager.GetString("NameComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: {0}.
        /// </summary>
        public static string PDCComment {
            get {
                return ResourceManager.GetString("PDCComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Raw {
            get {
                return ResourceManager.GetString("Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RID: {0}.
        /// </summary>
        public static string RIDComment {
            get {
                return ResourceManager.GetString("RIDComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only Domain Controller.
        /// </summary>
        public static string RodcComment {
            get {
                return ResourceManager.GetString("RodcComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once per hour.
        /// </summary>
        public static string Schedule1PerHour {
            get {
                return ResourceManager.GetString("Schedule1PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twice per hour.
        /// </summary>
        public static string Schedule2PerHour {
            get {
                return ResourceManager.GetString("Schedule2PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once every 3 hours.
        /// </summary>
        public static string Schedule3Hours {
            get {
                return ResourceManager.GetString("Schedule3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four times per hour.
        /// </summary>
        public static string Schedule4PerHour {
            get {
                return ResourceManager.GetString("Schedule4PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule: {0}.
        /// </summary>
        public static string ScheduleComent {
            get {
                return ResourceManager.GetString("ScheduleComent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        public static string ScheduleCustom {
            get {
                return ResourceManager.GetString("ScheduleCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string ScheduleNone {
            get {
                return ResourceManager.GetString("ScheduleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 x 7.
        /// </summary>
        public static string ScheduleNonStop {
            get {
                return ResourceManager.GetString("ScheduleNonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sch master: {0}.
        /// </summary>
        public static string SchMasterComment {
            get {
                return ResourceManager.GetString("SchMasterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site: {0}.
        /// </summary>
        public static string SiteComment {
            get {
                return ResourceManager.GetString("SiteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction: {0}.
        /// </summary>
        public static string TrustDirectionComment {
            get {
                return ResourceManager.GetString("TrustDirectionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string TrustTypeComment {
            get {
                return ResourceManager.GetString("TrustTypeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n{1}.
        /// </summary>
        public static string TwoLineStr {
            get {
                return ResourceManager.GetString("TwoLineStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnKnown.
        /// </summary>
        public static string UnKnown {
            get {
                return ResourceManager.GetString("UnKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string Ver2000 {
            get {
                return ResourceManager.GetString("Ver2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2003.
        /// </summary>
        public static string Ver2003 {
            get {
                return ResourceManager.GetString("Ver2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008.
        /// </summary>
        public static string Ver2008 {
            get {
                return ResourceManager.GetString("Ver2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012.
        /// </summary>
        public static string Ver2012 {
            get {
                return ResourceManager.GetString("Ver2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016.
        /// </summary>
        public static string Ver2016 {
            get {
                return ResourceManager.GetString("Ver2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        public static string Ver2019 {
            get {
                return ResourceManager.GetString("Ver2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2000.
        /// </summary>
        public static string Win2000 {
            get {
                return ResourceManager.GetString("Win2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2000 Mixed Mode.
        /// </summary>
        public static string Win2000Mix {
            get {
                return ResourceManager.GetString("Win2000Mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2000 Native Mode.
        /// </summary>
        public static string Win2000Native {
            get {
                return ResourceManager.GetString("Win2000Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2003 Interim.
        /// </summary>
        public static string Win2003Interim {
            get {
                return ResourceManager.GetString("Win2003Interim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2003 Native.
        /// </summary>
        public static string Win2003Native {
            get {
                return ResourceManager.GetString("Win2003Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2008.
        /// </summary>
        public static string Win2008 {
            get {
                return ResourceManager.GetString("Win2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 2008 R2.
        /// </summary>
        public static string Win2008R2 {
            get {
                return ResourceManager.GetString("Win2008R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server 2012.
        /// </summary>
        public static string Win2012 {
            get {
                return ResourceManager.GetString("Win2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server 2012 R2.
        /// </summary>
        public static string Win2012R2 {
            get {
                return ResourceManager.GetString("Win2012R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server 2016.
        /// </summary>
        public static string Win2016 {
            get {
                return ResourceManager.GetString("Win2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server 2019.
        /// </summary>
        public static string Win2019 {
            get {
                return ResourceManager.GetString("Win2019", resourceCulture);
            }
        }
    }
}
