//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mihelcic.Net.Visio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mihelcic.Net.Visio.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Topology Diagrammer.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMnu {
            get {
                return ResourceManager.GetString("AboutMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorcode Servers per Domain.
        /// </summary>
        public static string ColorcodeServers {
            get {
                return ResourceManager.GetString("ColorcodeServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this Box if you would like in the drawing Servers color coded depending of Domain..
        /// </summary>
        public static string ColorcodeServersToolTip {
            get {
                return ResourceManager.GetString("ColorcodeServersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationConfiguration.xml.
        /// </summary>
        public static string ConfigurationFile {
            get {
                return ResourceManager.GetString("ConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string ContentsMnu {
            get {
                return ResourceManager.GetString("ContentsMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLbl {
            get {
                return ResourceManager.GetString("DescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory authentication.
        /// </summary>
        public static string DirectoryAuthenticationTitle {
            get {
                return ResourceManager.GetString("DirectoryAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain:.
        /// </summary>
        public static string DomainLbl {
            get {
                return ResourceManager.GetString("DomainLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw!.
        /// </summary>
        public static string DrawBtn {
            get {
                return ResourceManager.GetString("DrawBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw FQDN Server Names.
        /// </summary>
        public static string DrawFQDNServerNames {
            get {
                return ResourceManager.GetString("DrawFQDNServerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this Box if you would like to have the Fully qualified server names in the drawing..
        /// </summary>
        public static string DrawFQDNServerNamesToolTip {
            get {
                return ResourceManager.GetString("DrawFQDNServerNamesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Cacelled.
        /// </summary>
        public static string DrawingCancelled {
            get {
                return ResourceManager.GetString("DrawingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Servers.
        /// </summary>
        public static string DrawServers {
            get {
                return ResourceManager.GetString("DrawServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMnu {
            get {
                return ResourceManager.GetString("ExitMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMnu {
            get {
                return ResourceManager.GetString("FileMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest:.
        /// </summary>
        public static string ForestLabel {
            get {
                return ResourceManager.GetString("ForestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Forest Dns name.
        /// </summary>
        public static string ForestToolTip {
            get {
                return ResourceManager.GetString("ForestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMnu {
            get {
                return ResourceManager.GetString("HelpMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Server Version.
        /// </summary>
        public static string IncludeServerVersion {
            get {
                return ResourceManager.GetString("IncludeServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this Box if you would like to have the OS Version Number included in the drawing..
        /// </summary>
        public static string IncludeServerVersionToolTip {
            get {
                return ResourceManager.GetString("IncludeServerVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here comes status.
        /// </summary>
        public static string InitialStatus {
            get {
                return ResourceManager.GetString("InitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMnu {
            get {
                return ResourceManager.GetString("LanguageMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files.
        /// </summary>
        public static string LogFiles {
            get {
                return ResourceManager.GetString("LogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOn.
        /// </summary>
        public static string LogOnBtn {
            get {
                return ResourceManager.GetString("LogOnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Topology Diagrammer.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Solution Architect.
        /// </summary>
        public static string MyTitle {
            get {
                return ResourceManager.GetString("MyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKBtn {
            get {
                return ResourceManager.GetString("OKBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLbl {
            get {
                return ResourceManager.GetString("PasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty to automatically select target Server or enter valid server name.
        /// </summary>
        public static string ServerToolTip {
            get {
                return ResourceManager.GetString("ServerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranging Diagram.
        /// </summary>
        public static string StatusArranging {
            get {
                return ResourceManager.GetString("StatusArranging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Data....
        /// </summary>
        public static string StatusCollecting {
            get {
                return ResourceManager.GetString("StatusCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Domain Information.
        /// </summary>
        public static string StatusCollectingDomains {
            get {
                return ResourceManager.GetString("StatusCollectingDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting General Information.
        /// </summary>
        public static string StatusCollectingGeneral {
            get {
                return ResourceManager.GetString("StatusCollectingGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Site Information.
        /// </summary>
        public static string StatusCollectingSites {
            get {
                return ResourceManager.GetString("StatusCollectingSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Completed.
        /// </summary>
        public static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected....
        /// </summary>
        public static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string StatusConnectionFailed {
            get {
                return ResourceManager.GetString("StatusConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Connections.
        /// </summary>
        public static string StatusConnections {
            get {
                return ResourceManager.GetString("StatusConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Visio Document.
        /// </summary>
        public static string StatusCreating {
            get {
                return ResourceManager.GetString("StatusCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving CSV data....
        /// </summary>
        public static string StatusCsv {
            get {
                return ResourceManager.GetString("StatusCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Nodes.
        /// </summary>
        public static string StatusNodes {
            get {
                return ResourceManager.GetString("StatusNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Visio Document.
        /// </summary>
        public static string StatusSaving {
            get {
                return ResourceManager.GetString("StatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving XML data....
        /// </summary>
        public static string StatusXml {
            get {
                return ResourceManager.GetString("StatusXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsMnu {
            get {
                return ResourceManager.GetString("ToolsMnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string UserLbl {
            get {
                return ResourceManager.GetString("UserLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ValidateBtn {
            get {
                return ResourceManager.GetString("ValidateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated.
        /// </summary>
        public static string Validated {
            get {
                return ResourceManager.GetString("Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate settings first.
        /// </summary>
        public static string ValidateFirst {
            get {
                return ResourceManager.GetString("ValidateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation in progress.
        /// </summary>
        public static string ValidationProgress {
            get {
                return ResourceManager.GetString("ValidationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLbl {
            get {
                return ResourceManager.GetString("VersionLbl", resourceCulture);
            }
        }
    }
}
